name: sealed_flutter_bloc
description: flutter_bloc state management extension that integrates sealed_unions.
version: 8.0.2
repository: https://github.com/felangel/sealed_flutter_bloc
issue_tracker: https://github.com/felangel/sealed_flutter_bloc/issues
homepage: https://github.com/felangel/sealed_flutter_bloc
topics: [bloc, state-management]

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  bloc: ^8.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  sealed_unions: ^3.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: The sealed flutter bloc package logo.
    path: screenshots/logo.png
